In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("nba.csv")

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [7]:
df.head()
#to see the kind of values in the dataset

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [8]:
#to check which column can be picked as a categorical variable
df.dtypes

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [9]:
def age_group(age):
    if(age<=18):
        return 'Prodigy'
    elif(age>=18 and age<=25):
        return"Young player"
    elif(age>25 and age<=35):
        return"Experienced player"
    else:
        return'Legend player'
        
df['player_age']=df['Age'].apply(age_group)

In [10]:
categorical_var = "player_age"
stats = (
df.groupby(categorical_var)["Salary"]
.agg(['mean', 'median', 'min', 'max', 'std'])
)
stats
#this shows that an experienced player that whose age is between 25 and 3
#has the higher salary owing to their experience
#also legends have higher salary and young players due to their experience

,mean,median,min,max,std
player_age,,,,,
Experienced player,6.494939e+06,4637500.0,55722.0,22970500.0,5.839895e+06
Legend player,3.959600e+06,2834470.0,222888.0,25000000.0,5.273399e+06
Young player,2.983969e+06,1623120.0,30888.0,16407501.0,3.569683e+06

In [11]:
categorical_var = "Position"
stats = (
df.groupby(categorical_var)["Age"]
.agg(['mean', 'median', 'min', 'max', 'std'])
)
stats
#the center position players have the highest mean age because
#they need experience to play in that position
#shooting gaurds are generally runners so they need to be young
#therefore they have the lowest mean age

               mean  median   min   max       std
Position
C         27.371795    27.0  20.0  40.0  4.156388
PF        27.160000    27.0  20.0  40.0  4.607241
PG        26.847826    26.5  20.0  40.0  4.169314
SF        26.858824    26.0  20.0  38.0  4.386540
SG        26.539216    25.0  19.0  39.0  4.643043

In [14]:
categorical_var = "player_age"
stats = (
df.groupby(categorical_var)["Weight"]
.agg(['mean', 'median', 'min', 'max', 'std'])
)
stats
#young players have the least weight due to their running in the game

                          mean  median    min    max        std
player_age
Experienced player  224.659574   225.0  161.0  307.0  27.322760
Legend player       223.782609   228.0  172.0  260.0  24.483680
Young player        217.557789   215.0  165.0  280.0  24.986571

In [15]:
categorical_var = "Position"
stats = (
df.groupby(categorical_var)["Salary"]
.agg(['mean', 'median', 'min', 'max', 'std'])
)
stats
#the center position has the highest mean salary due to it
#being the most important position

                  mean     median       min         max           std
Position
C         5.967052e+06  3811060.0   83397.0  22359364.0  5.787989e+06
PF        4.562483e+06  2943221.0  111444.0  22192730.0  4.800054e+06
PG        5.077829e+06  3018463.5   55722.0  21468695.0  5.051809e+06
SF        4.857393e+06  2020540.0   30888.0  25000000.0  6.011889e+06
SG        4.009861e+06  2127840.0   55722.0  20000000.0  4.491609e+06

In [16]:
categorical_var = "Position"
stats = (
df.groupby(categorical_var)["Weight"]
.agg(['mean', 'median', 'min', 'max', 'std'])
)
stats
#the center player has the most weight due to his strength

                mean  median    min    max        std
Position
C         254.205128   250.0  220.0  307.0  15.974297
PF        240.430000   240.0  200.0  275.0  12.591688
PG        189.478261   190.0  161.0  220.0  11.422436
SF        221.776471   225.0  175.0  260.0  14.286504
SG        206.686275   209.5  175.0  234.0  12.857929

In [17]:
df.groupby('player_age')['Salary'].describe()
#this shows that an experienced player that whose age is between 25 and 3
#has the higher salary owing to their experience
#also legends have higher salary and young players due to their experienc

,count,mean,std,min,25%,50%,75%,max
player_age,,,,,,,,
Experienced player,230.0,6.494939e+06,5.839895e+06,55722.0,1499390.25,4637500.0,9939062.50,22970500.0
Legend player,22.0,3.959600e+06,5.273399e+06,222888.0,947276.00,2834470.0,4772004.75,25000000.0
Young player,194.0,2.983969e+06,3.569683e+06,30888.0,947276.00,1623120.0,3251516.75,16407501.0