In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

In [4]:
df = pd.read_csv('iris.csv')
df.head()

   Id  sepal.length  sepal.width  petal.length  petal.width variety
0   1           5.1          3.5           1.4          0.2  Setosa
1   2           4.9          3.0           1.4          0.2  Setosa
2   3           4.7          3.2           1.3          0.2  Setosa
3   4           4.6          3.1           1.5          0.2  Setosa
4   5           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.tail()

In [5]:
setosa = df[df['variety'].str.contains('setosa', case=False)]
display(setosa.describe().T[['mean', 'std', '25%', '50%', '75%']])

                mean        std    25%   50%     75%
Id            25.500  14.577380  13.25  25.5  37.750
sepal.length   5.006   0.352490   4.80   5.0   5.200
sepal.width    3.428   0.379064   3.20   3.4   3.675
petal.length   1.462   0.173664   1.40   1.5   1.575
petal.width    0.246   0.105386   0.20   0.2   0.300

In [6]:
versicolor = df[df['variety'].str.contains('versicolor', case=False)]
display(versicolor.describe().T[['mean', 'std', '25%', '50%', '75%']])

                mean        std     25%    50%    75%
Id            75.500  14.577380  63.250  75.50  87.75
sepal.length   5.936   0.516171   5.600   5.90   6.30
sepal.width    2.770   0.313798   2.525   2.80   3.00
petal.length   4.260   0.469911   4.000   4.35   4.60
petal.width    1.326   0.197753   1.200   1.30   1.50

In [ ]:
Virginica = df[df['variety'].str.contains('Virginica', case=False)]
display(Virginica.describe().T[['mean', 'std', '25%', '50%', '75%']])

                 mean        std      25%     50%      75%
Id            125.500  14.577380  113.250  125.50  137.750
sepal.length    6.588   0.635880    6.225    6.50    6.900
sepal.width     2.974   0.322497    2.800    3.00    3.175
petal.length    5.552   0.551895    5.100    5.55    5.875
petal.width     2.026   0.274650    1.800    2.00    2.300